CREATE TABLE venues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    capacity INTEGER NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    venue_id BIGINT,
    capacity INTEGER,
    price DOUBLE,
    category VARCHAR(255),
    city VARCHAR(255),
    PRIMARY KEY (id)
);
